_:
{
  imports = [
    ./configuration.nix
    ../../modules/nix.nix
    ../../modules/user.nix
    ../../modules/plasma.nix
    ../../modules/bashrc.nix
    ../../modules/lf.nix
    ../../modules/cli.nix
    ../../modules/media.nix
    ../../modules/services.nix
    ../../modules/fonts.nix
    ../../modules/git.nix
    ../../modules/parsec.nix
    ../../modules/vim.nix
    ../../modules/tmux.nix
  ];
}
