# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  # boot.kernelModules = [ "kvm-amd" ];
  boot.kernelModules = [ "bfq" ];
  # boot.extraModulePackages = [ ];
  boot.kernelParams = [ "mitigations=off" "nowatchdog" "nmi_watchdog=0" "quiet" "rd.systemd.show_status=auto" "rd.udev.log_priority=3" ];
  boot.initrd.luks.devices."luksroot" = {
    device="/dev/disk/by-uuid/4a283a90-7ef7-454a-a330-f906228876e3";
    preLVM=true;
    allowDiscards=true;
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a1565865-f199-48aa-8589-cda6d49648e6";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B102-6F47";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/10c04890-0442-4f3a-a581-411a0b5cb309";
      fsType = "ext4";
    };

  swapDevices = [ ];
}
